const {chromium}=require('../release/ui-check/node_modules/playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const out=path.join(root,'release/ui-check/screens');fs.mkdirSync(out,{recursive:true});
const credentials=JSON.parse(fs.readFileSync(path.join(root,'release/.outmax-deploy-credentials.json'),'utf8'));
const base='http://127.0.0.1:8877';
let runningBrowser;
(async()=>{
 const browser=runningBrowser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/login');await page.screenshot({path:path.join(out,'login-desktop.png')});
 await page.getByLabel('Логин',{exact:true}).fill(credentials.user);await page.getByLabel('Пароль',{exact:true}).fill(credentials.password);await page.getByRole('button',{name:'Войти в редактор'}).click();await page.locator('#account-name strong').waitFor();
 await page.screenshot({path:path.join(out,'editor-desktop.png')});
 await page.locator('#account-name').click();await page.screenshot({path:path.join(out,'profile-menu.png')});await page.locator('#all-articles').click();await page.locator('.archive-card').first().waitFor();
 await page.screenshot({path:path.join(out,'archive-desktop.png')});
 await page.getByRole('button',{name:'Список',exact:true}).click();await page.screenshot({path:path.join(out,'archive-list-desktop.png')});
 await page.locator('.account-dialog-head button').click();await page.locator('#account-name').click();await page.locator('#manage-users').click();await page.locator('.user-row').first().waitFor();await page.screenshot({path:path.join(out,'users-desktop.png')});
 await page.locator('#add-user').click();const form=page.locator('.account-user-dialog .user-form');await form.getByLabel('Имя',{exact:true}).fill('Александра Вишневская-Ковальчик');const login='ui-check-'+Date.now();await form.getByLabel('Логин',{exact:true}).fill(login);await form.locator('[name=role]').selectOption('moderator');
 await page.screenshot({path:path.join(out,'new-user.png')});const createdPromise=page.waitForResponse(r=>r.url()===base+'/editor-api/users'&&r.request().method()==='POST');await form.getByRole('button',{name:'Добавить пользователя',exact:true}).click();const created=await (await createdPromise).json();assert.equal(created.role,'moderator');assert.ok(created.password.length>=8);
 const credentialsBox=page.locator('.account-user-dialog[aria-label="Данные входа нового пользователя"]');await credentialsBox.waitFor();await credentialsBox.getByRole('button',{name:'Готово',exact:true}).click();await page.locator('.user-row').filter({hasText:login}).waitFor();
 const all=await (await context.request.get(base+'/editor-api/users')).json();const moderator=all.find(u=>u.id==='ivan-nekrut'),editor=all.find(u=>u.id==='editor-01');
 const modContext=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await modContext.request.post(base+'/login',{form:{login:moderator.login,password:moderator.password}});const mod=await modContext.newPage();mod.on('pageerror',e=>errors.push(e.message));await mod.goto(base);await mod.locator('#account-name strong').waitFor();assert.equal(await mod.locator('#manage-users').isVisible(),false);
 await mod.locator('#account-name').click();await mod.locator('#team-articles').click();await mod.locator('#archive-owner').waitFor();await mod.locator('#archive-owner').selectOption(editor.id);await mod.locator('#archive-caption').filter({hasText:'только просмотр'}).waitFor();await mod.locator('.archive-card').first().waitFor();assert.equal(await mod.getByRole('button',{name:'Удалить статью',exact:true}).count(),0);
 await mod.screenshot({path:path.join(out,'moderator-archive.png')});const original=await (await modContext.request.get(base+'/editor-api/archive/'+editor.id)).json();const item=original[0];
 await mod.locator('.archive-open').first().click();await mod.locator('.account-viewer').waitFor();await mod.frameLocator('.account-viewer iframe').locator('h1').waitFor();assert.ok(await mod.frameLocator('.account-viewer iframe').locator('img').evaluate(img=>img.complete&&img.naturalWidth>0));await mod.screenshot({path:path.join(out,'readonly-article.png')});await mod.getByRole('button',{name:'Телефон',exact:true}).click();assert.ok((await mod.locator('.account-viewer iframe').boundingBox()).width<=390);
 const copyPromise=mod.waitForResponse(r=>r.url().includes('/copy?')&&r.request().method()==='POST');await mod.locator('.account-viewer').getByRole('button',{name:'Сохранить копию себе',exact:true}).click();const copied=await (await copyPromise).json();await mod.getByRole('button',{name:'Открыть мою копию',exact:true}).click();await mod.locator('.account-viewer').waitFor({state:'detached'});await mod.locator('.account-dialog').waitFor({state:'hidden'});assert.equal(await mod.locator('#filename').inputValue(),copied.id);
 await mod.locator('#page-title').fill('Отредактированная личная копия');await mod.locator('#save').click();await mod.locator('#status').filter({hasText:'Сохранено'}).waitFor();const originalAfter=await (await modContext.request.get(base+'/editor-api/archive/'+editor.id)).json();assert.deepEqual(originalAfter,original);await modContext.request.delete(base+'/editor-api/draft/'+copied.id+'?brand='+copied.brand);
 const editorContext=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await editorContext.request.post(base+'/login',{form:{login:editor.login,password:editor.password}});const mobile=await editorContext.newPage();mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base);await mobile.locator('#account-name strong').waitFor();assert.equal(await mobile.locator('#team-articles').isVisible(),false);await mobile.locator('#account-name').click();await mobile.screenshot({path:path.join(out,'menu-mobile.png')});await mobile.locator('#all-articles').click();await mobile.locator('.archive-card').first().waitFor();await mobile.screenshot({path:path.join(out,'archive-mobile.png')});assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await mobile.getByRole('button',{name:'Удалить статью',exact:true}).first().click();await mobile.locator('.account-confirm').waitFor();await mobile.getByRole('button',{name:'Нет, оставить'}).click();assert.equal((await (await editorContext.request.get(base+'/editor-api/archive/'+editor.id)).json()).length,3);
 await page.locator('.account-dialog-head button').click();
 await page.route('**/editor-api/me',async route=>{const response=await route.fetch();await route.fulfill({response,json:{...await response.json(),name:'Александра Вишневская-Ковальчик'}});});
 await page.reload();await page.locator('#account-name strong').waitFor();await page.setViewportSize({width:320,height:812});await page.screenshot({path:path.join(out,'header-long-name-320.png')});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.setViewportSize({width:1440,height:1000});
 let mode='demo';const demo=Array.from({length:8},(_,i)=>({id:'fixture-'+i,brand:i%2?'hasl':'outmax',title:['Осенняя коллекция: новые цвета и материалы','Подбираем размер и посадку','Обзор моделей для ежедневных прогулок'][i%3],preview:'Подробный материал о выборе обуви и повседневном стиле.',image:'/images/outmax.png',createdAt:'2026-10-02T10:30:00+07:00',savedAt:'2026-10-02T14:00:00+07:00'}));
 const worst=demo.map((x,i)=>({...x,title:['Александра Вишневская-Ковальчик: полное руководство по выбору кроссовок для длинных осенних прогулок и активного отдыха всей семьёй','Как выбрать обувь — размеры, материалы, уход и сравнение моделей из новой коллекции OUTMAX / ХАСЛ','J','Обзор коллекции <b>Осень</b> & повседневного стиля'][i%4],preview:i%2?'Очень длинное описание материала о выборе обуви, которое не должно вытеснить даты или кнопки управления.':'',image:i===1?'https://example.test/missing.png':i===2?'':'/images/outmax.png',createdAt:i===3?'invalid-date':x.createdAt}));
 const huge=Array.from({length:1284},(_,i)=>({...demo[i%demo.length],id:'large-'+i,title:demo[i%demo.length].title+' · '+(i+1)}));
 const sets={demo,worst,empty:[],one:[demo[0]],huge};await page.route('**/editor-api/archive/admin',route=>route.fulfill({json:sets[mode]}));
 await page.locator('#account-name').click();await page.locator('#all-articles').click();await page.locator('.archive-card').first().waitFor();await page.exposeFunction('__fixtureMode',async value=>{mode=value;});
 await page.evaluate(()=>{const toggle=document.createElement('div');toggle.id='dev-fixture-toggle';toggle.style.cssText='position:fixed;bottom:5px;left:50%;transform:translateX(-50%);z-index:1000;padding:3px;border:1px solid #ddd;background:#eee;border-radius:7px;display:flex;gap:3px';for(const mode of ['demo','worst','empty','one','huge']){const b=document.createElement('button');b.textContent=mode;b.type='button';b.style.cssText='font:10px Arial;padding:5px 7px;min-height:26px';b.onclick=async()=>{await window.__fixtureMode(mode);document.querySelector('#archive-owner').dispatchEvent(new Event('change'));};toggle.append(b);}document.querySelector('.account-dialog').append(toggle);});
 for(const width of [1440,768,375,320]) {
  await page.setViewportSize({width,height:width<500?812:1000});
  for(const value of ['worst','empty','one','huge']) {await page.locator('#dev-fixture-toggle').getByRole('button',{name:value,exact:true}).click();if(value==='empty')await page.getByRole('heading',{name:'В архиве пока пусто'}).waitFor();else await page.locator('.archive-card').first().waitFor();if(value==='one')assert.match(await page.locator('#archive-caption').textContent(),/^1 статья/);if(value==='huge')assert.equal(await page.locator('.archive-card').count(),24);await page.screenshot({path:path.join(out,`fixture-${value}-${width}.png`)});const overflow=await page.locator('.account-dialog').evaluate(el=>el.scrollWidth>el.clientWidth+1);assert.equal(overflow,false,`dialog overflow: ${value} ${width}`);}
 }
 await page.setViewportSize({width:1440,height:1000});await page.locator('#dev-fixture-toggle').getByRole('button',{name:'worst',exact:true}).click();await page.locator('.archive-card').first().waitFor();await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.screenshot({path:path.join(out,'fixture-large-text.png')});
 assert.deepEqual(errors,[]);console.log('Browser checks: header, archive/list, mobile, new user, moderator preview/copy/edit, immutable source, delete cancellation, long data, empty/one/1284 articles: OK');console.log('Screenshots:',out);
 await browser.close();
})().catch(async error=>{console.error(error);if(runningBrowser)await runningBrowser.close();process.exitCode=1;});
